AWSTemplateFormatVersion: 2010-09-09

Description: Collator cloud resources

Parameters:
  CollatorImageUrl:
    Description: Collator docker image
    Type: String

  SshPublicKey: #TODO one key 4 each collator
    Type: String
    Description: SshPublicKey  

  ServiceName:
    Description: ECS service and task definition name
    Type: String
    Default: collators

  RelaychainNodeP2pPort:
    Description: P2P port for the embedded relaychain node
    Type: Number
    Default: 33334

  CollatorP2pPort:
    Description: P2P port for the collator itself
    Type: Number
    Default: 33333

  CollatorHttpPort:
    Description: HTTP RPC port for the collator
    Type: Number
    Default: 1833

  CollatorWsPort:
    Description: WS RPC port for the collator
    Type: Number
    Default: 1933

  ContainerCpu:
    Description: How much CPU to give the container. 1024 is 1 CPU
    Type: Number
    Default: 4096

  ContainerMemory:
    Description: How much memory in megabytes to give the container
    Type: Number
    Default: 8192

  DesiredCount:
    Description: How many copies of the service task to run
    Type: Number
    Default: 2

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
        ClusterName: !Sub ${AWS::StackName}-cluster     

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      Volumes:
        - Name: efsdata
          EFSVolumeConfiguration:
            FileSystemId: !ImportValue CollatorFileSystemId
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Ref CollatorImageUrl
          PortMappings:
            - ContainerPort: !Ref RelaychainNodeP2pPort
            - ContainerPort: !Ref CollatorP2pPort
            - ContainerPort: !Ref CollatorHttpPort
            - ContainerPort: !Ref CollatorWsPort
          MountPoints:
            - ContainerPath: /data
              SourceVolume: efsdata
          Ulimits:
            - HardLimit: 65536
              Name: nofile
              SoftLimit: 65536
          Environment:
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
            - Name: SSH_PUBLIC_KEY
              Value: !Ref SshPublicKey #TODO one key 4 each collator
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: collators
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: collator-node

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue CollatorSecurityGroupId
          Subnets:
            - !ImportValue PrivateSubnet1Id
            - !ImportValue PrivateSubnet2Id
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref CollatorHttpPort
          TargetGroupArn:
            Fn::ImportValue:
              CollatorTargetGroupArn