AWSTemplateFormatVersion: 2010-09-09

Description: Shared cloud auxiliary resources - targets eu-west-1

Parameters:
  PrivateSubnet1Id: 
    Type: String

  PrivateSubnet2Id: 
    Type: String

  MountTargetSecurityGroupId:
    Type: String

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
        ClusterName: !Sub ${AWS::StackName}-cluster     
        
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub ${AWS::StackName}-log-group
      RetentionInDays: 7

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      FileSystemTags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-file-system
  
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroups:
        - !Ref MountTargetSecurityGroupId

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivateSubnet2Id
      SecurityGroups:
        - !Ref MountTargetSecurityGroupId

Outputs:
  ExecutionRoleArn:
    Description: Execution role ARN for ECS tasks
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: CollatorExecutionRoleArn

  TaskRoleArn:
    Description: ECS task role ARN
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: CollatorTaskRoleArn

  ClusterId:
    Description: Id of the ECS cluster
    Value: !Ref Cluster
    Export:
      Name: CollatorClusterId

  FileSystemId:
    Description: Id of the shared elastic file system shared within the collator cluster
    Value: !Ref FileSystem
    Export:
      Name: CollatorFileSystemId

  MountTarget1Id:
    Description: EFS mount target 1 id
    Value: !Ref MountTarget1
    Export:
      Name: CollatorMountTarget1Id

  MountTarget2Id:
    Description: EFS mount target 2 id
    Value: !Ref MountTarget2
    Export:
      Name: CollatorMountTarget2Id